name = "Zelos Extension Xcp"
version = "0.1.0"
description = "XCP extension for Zelos"
author = "zeloscloud"
repository = "https://github.com/zeloscloud/zelos-extension-xcp"
icon = "assets/icon.svg"
readme = "README.md"

[config]
schema = "config.schema.json"

[host]
type = "agent"

[host.agent]
entry = "main.py"
python_version = "3.11"

[package]
paths = ["main.py", "zelos_extension_xcp"]
